//
//  FactModel.swift
//  FactsNigeria
//
//  Created by Oghosa Igbinakenzua on 2016-05-03.
//  Copyright © 2016 Oghosa Igbinakenzua. All rights reserved.
//

import GameKit

struct FactModel {
    let facts = [
        "Nigeria, with a 2013 estimated population of 174,507,539 is the most populous Black nation and the 7th most populated nation in the entire world, trailing after—from least to most—Pakistan, Brazil, Indonesia, USA, India and China (1.3bn).",
        "Nigerians are 1/5th the total population of Black Africa.",
        "Nigeria, with 521 languages has the fourth most in the world. This includes 510 living languages, two second languages without native speakers and 9 extinct languages.",
        "The Portuguese reached Nigeria in 1472. In 1880 the British began conquering Nigeria’s south. The north was conquered by 1903.",
        "Wole Soyinka is a Nigerian Nobel laureate. He wrote ‘Telephone Conversation!’",
        "With a net worth of $16.1bn, Nigeria’s Aliko Dangote is the richest Black person in the world.",
        "Yoruba and their bloodlines worldwide have the highest rate of twinning (having twins) in the world.",
        "The 2006 Census found Nigerians to be the highest educated ethnic or racial group in America.",
        "The Northern knot, Arewa insignia has Christian origins, investigation by Ibraheem A. Waziri revealed. It is adapted from the Church Celtic knot.",
        "Pre-tribalism: Malam Umaru Altine, a northern Fulani man was the first elected Mayor of Enugu, in the east, and was even re-elected for a second term.",
        "Pre-tribalism: John Umoru, from Etsako in today’s Edo State (Western region) was elected for the House of Assembly to represent Port Harcourt in the Eastern Nigerian House of Assembly.",
        "The Colonial Cantonments Proclamation of 1914 established ‘foreign quarters,’ ‘Sabon Gari,’ institutionalizing the Sabon Garuruwa system of ‘foreigner’ residential segregation in Nigeria.",
        "Crispin Curtis Adeniyi-Jones (1876-1957) who the street in Ikeja, ‘Adeniyi-Jones’ was named after, was a medical director from Sierra Leone (a Saro). As a co-founder of NNDP, he won one of the Lagos 3 legislative council seats in 1923 and represented Nigerians for 15 yrs.",
        "Saros was the name given to 19th and 20th century ‘Creole’ African literati migrants from Sierra Leone.",
        "Amaros was the name for repatriated Brazilian and Cuban slaves; the ‘Aguda’ people of Lagos today. This Brazilian community includes deportees of the brave “Malê Revolt” in Portugal.",
        "British colonization was not all voluntary ‘happy slave trade,’ but involved brutal terror against non-cooperation and stiff opposition. Captain Lord Esme Gordon Lenox, ‘With The West African Frontier Force,’ describes: “…we stormed down to Amassana, which was a town supposed to be friendly and fined them 25 goats and 20 chickens for non-assistance, then returned to Agbeni and burned half…October 1st was spent in continuance of yesterdays incendiraism by burning every town or farm we could see. I shudder to think of how many houses we have destroyed in these two days. On our way back to Egbbeddi in the afternoon we passed by Sabagreia and told our old friend Chief Ijor that most likely we should burn down Sabagreia the next day…”",
        "Nigeria’s population was just 16 million in 1911. It is projected to hit 444 million by 2050, surpassing the US and becoming the 4th largest in the world.",
        "The population of Lagos today is about more than the total population of all Eastern states combined.",
        "Lagos’ population in 1872 was 60,000. By 2015 it will be the third largest city in the entire world.",
        "Nigeria’s north (719,000 sq. km), occupies 80% of Nigeria’s land mass. In size it is four times the South.",
        "1st republic Aviation Minister, Chief Mbazulike Amaechi hid former South African President, Nelson Mandela, for six months in Nigeria to evade his arrest by the apartheid regime.",
        "Gangsta: In 1984 under the disciplinary Buhari/Idiagbon government, there was a sophisticated attempt to kidnap and repatriate ex-civilian regime minister of transport, Umaru Dikko from the UK, anesthetized in a freight crate, for the embezzlement of $1bn under the Shagari regime.",
        "Valor: Part of the ‘Forgotten Army,’ Nigerians volunteered to fight with the allied forces among the 81st and 82nd West African Divisions, in the Second World War.",
        "The Adubi war in 1918 was a major uprising by 30,000 Abeokuta Ebga warriors against the colonial government for colonization, taxation and slave labor. One British was killed and rail and telegraph lines destroyed. The British rewarded their soldiers with medals for quelling the uprising. Awape Adediran a Molashin/ Kingmaker was imprisoned for his active involvement.",
        "Activist Mrs. Fumilayo Ransome-Kuti travelled widely, including to the Eastern bloc (Hungary, USSR and China where she met Mao Zedong). These interactions angered Nigeria, Britain and America. America called her a communist and refused her a U.S. Visa.",
        "Mrs. Fumilayo Ransome-Kuti, legendary Fela’s mother, was one of the delegates that negotiated Nigeria’s independence in Britain.",
        "Once upon a time, the north was the more literate part of Nigeria. According to Lord Luggard, there were 25,000 Qur’anic Arabic schools with about 250,000 pupils in the north.",
        "Sardauna of Sokoto said he preferred foreign workers to Igbo’s because he felt Igbo’s are domineering. This was while Nigeria existed as regions with regional administrations.",
        "Kaduna Nzeogwu killed Sardauna in Nigeria’s first military coup.",
        "In 1966, a mischievous Igbo owned bakery allegedly made a loaf of bread with a label that depicted Nzeogwu as the Saint in the ‘Saint George and the Dragon’ medieval tale, killing Sardauna, the ‘dragon,’ this labeled bread provoked deadly anti-Igbo riots.",
        "Idrîs Aloma (1571-1603) King of Kanem-Bornu went on pilgrimage and came across firearms. He brought some guns back, along with Turks to train his army on how to use them.",
        "Travel Visa was not required to travel to the United Kingdom till 1984.",
        "A brand new car sold for N2000 in 1975. A ticket to London was less than N100 in 1975.",
        "In 1976, 75 kobo exchanged for one British Pound and 60 kobo for one US dollar.",
        "A dollar was 90 kobo at the beginning of Babangida’s term in 1985.",
        "Nigeria took its first loan from the World Bank in 1977.",
        "Obasanjo’s first term and Babangida’s regime oversaw the weakening of the naira.",
        "General Buhari and Idiagbon rejected IMF demands that Nigeria devalue its currency.",
        "Babangida’s coup in 1985 was invaluable to the colonialists suspected to have been in support as it led to Nigeria accepting SAP restrictions, loans and crippling foreign monetary conditions.",
        "Nigeria has 5 of the 10 richest pastors in the entire world, with net worth’s according to Forbes, from $10-150 million. They are Pastors, David Oyedepo, E. A. Adeboye, Chris Oyakhilome, Mathew Ashimolowo and Temitope Joshua.",
        "Nigeria has the 4th highest number of poor, living under a dollar a day in the entire world. 100 million are ‘destitute’ according to figures from the NBS (National Bureau of Statistics).",
        "Nigeria, the biggest economy in Africa is 160th out of 177 countries in HDI (Human Development Index).",
        "Nigeria has the highest paid legislators in the entire world.",
        "Based on amount squandered, of an income of $81 billion per year, Nigeria is the most corrupt nation in the world.",
        "The nation with the most defrauded people, aka ‘mugus,’ in history, is Nigeria. Successive administrations continue to loot a greater percentage of the nation’s wealth, running in hundreds of billions of dollars.",
        "Nigeria in 2013 was rated the worst country to be born based on welfare and prosperity projection.",
        "Aliko Dangote funded Presidents Obasanjo, Yar’Adua and Jonathan’s 4th republic campaigns. Buhari rejected funding from Dangote.",
        "Usman dan Fodio (1754–1817) was trained in classical Islamic science, philosophy and theology and wrote over 100 books on society, culture, religion, governance and politics. He could only declare Jihad when he was made leader in Gudu {In Islam you can only declare Jihad if you are an official Muslim leader}.",
        "The Borno Empire rejected Dan Fodio’s colonization jihad. Al-Hajj Muhammad al-Amîn ibn Muhammad al-Kânemî not only militarily defended his Empire, but also did so by religious, theological, legal and political debates, challenging why a Muslim Empire should colonize another.",
        "Kano history has it that a great warrior princess Magajiya Maimuna led her cavalry from Zaria to conquer Kumbwada.",
        "Kumbwada in Kano today is ruled by Queen Hajiya Haidzatu Ahmed, who presides over up to half a million subjects. A throne curse which makes men sick and die, keeps males off the throne. {Sadly, the woman ruled Kumbwada is the least funded chiefdom in Nigeria}.",
        "The Igbo ethnic group are the ‘Jews’ of Nigeria. Eager for a home state and highly entrepreneurial; during the Biafra secession attempt in the 60’s, this industrious people were already constructing indigenous tanks and other weaponry.",
        "There are several Nigerian officials in the government of English speaking The Gambia.",
        "There is a Nigerian origin, Yoruba chief in Accra. Chief Brimah is the only foreign Chief with a seat in the Ghanaian traditional council.",
        "Cross River State: The Ejagham (Ekoi) people in the Southeast are believed to have originated the Nsibidi (Nsibiri) writing system which later spread to the Efik, Igbo, Ibibio, Efut, Banyang and Annag peoples.",
        "Discovered in 1928, Nigeria’s North and North Central region hosts West Africa’s oldest civilization; the Nok, which flourished between 1000 BC and 300 BC. {Nok sculptures recently went on display disappointingly in Germany (not Africa).}",
        "Finished in 1460 the Benin Iya or moat is a historic world defense wonder. Spanning 1,200 kilometers with walls as high as 18 metres, it is the world’s largest archeological structure.",
        "Sungbo’s Eredo in Ogun state (6°49′N, 3°56′E) is a 100 mile system of up to 70 ft trenches and walls around Ijebu-Ode. It’s Queen, Bilkisu Sungbo has been attributed to the Biblical Queen Sheeba (Queen Bilkis in Quran).",
        "Lord Lugard estimated in 1904 that there were 170 walled towns still in existence in the whole of just the Kano province of northern Nigeria. He described Kano: ‘Commercial emporium of the western Sudan.’ Of its wall, he said, ‘I have never seen, nor even imagined, anything like it in Africa.’",
        "Osun: Queen Luwo, the twenty-first Ooni (ruler) of Ile-Ife paved the streets with quartz pebbles—and broken pottery, in 1000AD. The architecture had decorations that originated from Ancient America.",
        "Borno: The capital city of Kanem-Borno, Ngazargamu, was one of the largest cities in 1658 AD; the metropolis housed “about quarter of a million people” and had 660 well planned, wide and unbending streets.",
        "In 1246 AD the Kanemi of Borno created a sensation in Tunisia when he sent a gift of a giraffe to Al-Mustapha, king of Tunis.",
        "Sokoto: Two-story buildings with constructions glazed with tsoluwa, (laterite gravel), 10 mile circumference city walls, some as high as 20 feet, is how 16th century Surame, a Sokoto metropolis created by empire ruler, Muhammadu Kanta Sarkin Kebbi, was. UNESCO describes Surame as “one of the wonders of human history, creativity and ingenuity.”",
        "Kano: In 1851, this city, one of the largest in Africa, made 10 million sandal pairs and 5 million hides for export every year.",
        "Kebbi: Nigeria’s Sorko Sea lords of Kebbi state, made ships (Kanta) which were used for far away expeditions, including the 1311 AD, 2000 ship, famous voyage of Songhai Empire’s Mansa Abubakari II to the America’s, decades before Columbus.",
        "Yobe: The oldest discovered boat in Africa, and 3rd oldest on the world, the 8500 yr old Dufuna canoe was discovered by a Fulani herdsman in 1987 in Dufuna village, Fune LGA.",
        "Ondo: Confusing evolution scientists, the 13,000 yr old Iwo-Eleru cave skull, the oldest human fossil remains found in West Africa, has ‘ancient’ (140,000 yr old Laetoli) features, yet lived in more modern times.",
        "Benin Kingdom: The high quality and highly sophisticated bronze work of the Benin Kingdom dating as far back as the 13th century is a world wonder. Great works in iron, wood, ivory, and terra cotta products also highlight the empire’s history.",
        "Benin Kingdom: Lourenco Pinto, captain of a ship that carried missionaries to Warri in 1619, described Benin kingdom, ‘Great Benin where the king resides is larger than Lisbon, all the streets run straight and as far as the eyes can see….’",
        "Akwa Ibom: King Jaja of Opobo (1821–1891) founded Opobo city-state in 1867 and shipped palm oil to Britain independently of British middle men.",
        "Ancient Greeks appear to have Nigerian roots as supported by the Benin Haplogroup or Haplogroup 19. According to Jide Uwechia, ‘The Benin Haplotype (which originates from Nigeria, West Africa) accounts for HbS associated chromosomes in Sicily Northern Greece.’",
        "Ilorin’s Oba Afonja utilized Fulani warriors to help rebel against the Oyo Empire. The warriors after defeating Oyo took over Ilorin and Sheikh Alimi, their leader’s son became the first Emir.",
        "Much of north Nigeria was part of the Songhai Empire. Muhammad Kanta annexed Kebbi and other states between 1512 and 1517.",
        "The Obasanjo military regime converted Nigeria from a Parliamentary system to a Presidential system of government.",
        "Much of traditional pre-colonial Nigeria operated a parliamentary form of government. The council of elders could make or impeach the King.",
        "General Johnson Thomas Umurakwe Aguiyi-Ironsi on 24 May 1966, with Decree No. 34, dissolved Nigeria’s regions, creating provinces. He unified Regional Public Services under a single Commission. Riots were provoked in Kano and mutiny in Abeokuta; eventually there was a coup.",
        "In 1967 Gowon split the four regions into 12 states.",
        "Gowon’s Decree No. 8 of 1967 after the Aburi conference restored Nigeria as a confederacy.",
        "Late President Murtala Muhammed’s dad, Pam Azatus Iyok was from Dogon-Gaba, near Vom in Plateau state, Nigeria’s Middle Belt. Pam became a Muslim and married Ramat from Kano. Murtala Muhammed’s wife, Hafsat Ajoke was a Yoruba lady.",
        "Ex- President Yakubu Gowon from Jos state (Middle Belt) is a Christian. General Obasanjo was his Army chief who helped him defeat the Biafra attempted secession from 1967-1970.",
        "Nigeria has been ruled for 30 years by Christians (25 years if Azikiwe is excluded).",
        "Mujahid Asari Dokubo, the leader of the southern Movement for Emancipation of the Niger Delta (MEND) and the most vocal enemy of the north, is a Muslim.",
        "Nigeria is not roughly divided between a Muslim north and a Christian South. The far north, east and far south do have concentrations, but the rest of the nation defies such demarcations.",
        "In the Southwest, Osun, Lagos, Ogun and Oyo have a higher population of Muslims than Christians according to counts. Benue, Nasarawa and Plateau in the north have Christian majorities.",
        "According to the Senate joint committee, Nigeria’s chief terrorist leader, Abubakar Shekau is not a Nigerian; he hails from Niger republic. {Shekau is believed by security services to be deceased.}",
        "According to current demographics, after Hausa-Fulani (29%), Yoruba (21%), Igbo (18%) and Ijaw (10%) comes Kanuri (4%) and then Ibibio (3.5%) and Tiv (2.5%).",
        "Not really a northern caucus, but it was late M. K. O. Abiola that orchestrated and sponsored the Buhari /Idiagbon coup and then again the Babangida coup overthrow of Buhari. –Shagari memoir, “Beckoned to Serve;” Babangida, “Karl Maier – Midnight in Nigeria.” (Max Siollun)",
        "The leading caucus is basically a childhood friendship: President Obasanjo was childhood friends with President Babangida, President Abacha and Commander Danjuma.",
        "President Babangida was childhood friends with President Abdulsalam.",
        "President Obasanjo graduated Abdulsalam who later became President and went on to hand over power to democratically arranged President Obasanjo.",
        "Under the Presidential system, Nigerians have had 7 years total Northern rule and 11+ years Southern rule.",
        "Total civilian rule, Parliamentary and Presidential, Nigeria has had 12 years Northern and 11+ years Southern rule.",
        "6 coups is the highest number of any nation in Africa. Nigeria along with Sierra Leone, Ethiopia, Uganda and Mauritania are the nations with 6 coups.",
        "The Biafra war included a ‘Mid West invasion.’ The Midwest was either a battle field or in Biafra’s sights—Dr. Nowamagbe A. Omoigui relays.",
        "The Biafra 12th battalion headed by Lt Col Victor Adebukunola Banjo captured Benin and set out to capture Ibadan and Lagos.",
        "The Biafra 13th battalion, led by Ivenso entered Kwara, now Kogi and captured Okene, Atanai and Iloshi.",
        "Cameroon was an administrative part of Nigeria in 1945, hence the NCNC party (National Council of Nigeria and the Cameroons). Towards independence the UN mandated British held former German territory, south Cameroon opted to join French Cameroon and not Nigeria.",
        "J.C. Vaughn, Ernest Ikoli, H.O. Davies, Obafemi Awolowo and Sam Tsuiuel Akinsanya founded the Nigerian Youth Movement (NYM) in 1934 to promote national unity particularly between Yoruba and Igbo.",
        "Azikiwe left Nigerian Youth Movement (NYM) because he claimed the organization had been seized by Yoruba’s and it discriminated against Igbo’s including himself.",
        "Oyo defeats Ashanti: In 1764 the Ashanti army marched on Dahomey, Togo. At Atakpamé, the Ashanti army was ambushed and sacked by Dahomean infantry and female elite soldiers allied with forces from the Oyo Empire. Ashanti King Kusi Obodum was destooled after the defeat."]
    
    
    func getRandomFact() -> String {
        let randomNumber = GKRandomSource.sharedRandom().nextIntWithUpperBound(facts.count)
        return facts[randomNumber]
    }
}